mangling_schedule:
  - type: unary
    rules:
      - capitalize
      - toggle_case
    labels:
      - PERSON
      - ORG

  - type: binary
    rules:
      - join
    labels:
      - PERSON
      - ORG

  - type: unary
    rules:
      - nothing
    labels:
      - PERSON
